"""
generate_setup_notebook.py

Produces the source code of a Databricks 00_setup.py notebook from an entity config module.
Returns a string — the caller writes it to disk or uploads it directly.
"""
import pprint
import textwrap


def generate(config, catalog: str, dq_schema: str) -> str:
    """Return complete 00_setup.py notebook source for the given entity config."""
    entity = config.ENTITY
    parts  = []

    # ── header ────────────────────────────────────────────────────────────────
    parts.append("# Databricks notebook source")
    parts.append("")
    parts.append("# MAGIC %md")
    parts.append(f"# MAGIC # DQ Framework Setup - {entity}")
    parts.append("# MAGIC")
    parts.append("# MAGIC Idempotent setup generated by dq_framework/generate_setup_notebook.py.")
    parts.append("# MAGIC Run once per environment. Safe to re-run (all writes use MERGE or IF NOT EXISTS).")
    parts.append("")

    # ── widget parameters ──────────────────────────────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append(_widget_block(config, catalog, dq_schema))

    # ── imports ────────────────────────────────────────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append("from pyspark.sql import Row, functions as F")
    parts.append("from datetime import date")
    parts.append("")

    # ── Step 1 : create dq_rules_generic ──────────────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append("# MAGIC %md ## Step 1 - Create dq_rules_generic (if not exists)")
    parts.append("")
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append(
        "spark.sql(f\"CREATE TABLE IF NOT EXISTS {catalog}.{dq_schema}.dq_rules_generic "
        "(generic_rule_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), "
        "generic_rule_desc_short STRING NOT NULL, rule_description STRING, dq_category STRING, "
        "rule_detail STRING, rule_logic_template STRING, applicable_types STRING, "
        "bcbs239_principle STRING, solvencyii_pillar STRING, active INTEGER, "
        "created_date DATE, created_by STRING) USING DELTA "
        "COMMENT 'Generic DQ rule catalogue. generic_rule_id auto-increments.'\")"
    )
    parts.append("print(\"dq_rules_generic ready\")")
    parts.append("")

    # ── Step 2 : merge new generic rules (optional) ───────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    if config.NEW_GENERIC_RULES:
        parts.append("# MAGIC %md ## Step 2 - Merge new generic rules")
        parts.append("")
        parts.append("# COMMAND ----------")
        parts.append("")
        parts.append(_new_generic_rules_block(config))
    else:
        parts.append("# MAGIC %md ## Step 2 - No new generic rules for this entity")
        parts.append("")
        parts.append("# COMMAND ----------")
        parts.append("")
        parts.append(f"print(\"No new generic rules to merge for {entity}.\")")
        parts.append("")

    # ── Step 3 : create + merge validation request ────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append("# MAGIC %md ## Step 3 - Create dq_validation_request (if not exists) and merge")
    parts.append("")
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append(_validation_request_block(config))

    # ── Step 4 : copy source table ────────────────────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append("# MAGIC %md ## Step 4 - Copy source table into DQ schema (if not exists)")
    parts.append("")
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append(_copy_table_block(config))

    # ── Step 5 : create + merge rule mappings ─────────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append("# MAGIC %md ## Step 5 - Create dq_rule_mappings (if not exists) and merge")
    parts.append("")
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append(_rule_mappings_block(config))

    # ── Step 6 : create dq_results ────────────────────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append("# MAGIC %md ## Step 6 - Create dq_results (if not exists)")
    parts.append("")
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append(
        "spark.sql(f\"CREATE TABLE IF NOT EXISTS {catalog}.{dq_schema}.dq_results "
        "(dq_run_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), "
        "dq_execution_timestamp TIMESTAMP NOT NULL, dq_rule_no STRING NOT NULL, "
        "dq_number_relevant_records BIGINT NOT NULL, dq_number_pos_results BIGINT NOT NULL) "
        "USING DELTA COMMENT 'Aggregated DQ results. dq_run_id auto-increments.'\")"
    )
    parts.append("print(\"Table dq_results ready.\")")
    parts.append("")

    # ── footer ─────────────────────────────────────────────────────────────────
    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append("print(\"\\nSetup complete. All tables in DQ schema:\")")
    parts.append("spark.sql(f\"SHOW TABLES IN {catalog}.{dq_schema}\").show(truncate=False)")
    parts.append("")

    return "\n".join(parts)


# ── private helpers ────────────────────────────────────────────────────────────

def _widget_block(config, catalog, dq_schema):
    lines = []
    lines.append("try:")
    lines.append("    catalog = dbutils.widgets.get(\"catalog\")")
    lines.append("except:")
    lines.append(f"    catalog = {catalog!r}")
    lines.append("")
    lines.append("try:")
    lines.append("    dq_schema = dbutils.widgets.get(\"dq_schema\")")
    lines.append("except:")
    lines.append(f"    dq_schema = {dq_schema!r}")
    lines.append("")
    lines.append("try:")
    lines.append("    source_catalog = dbutils.widgets.get(\"source_catalog\")")
    lines.append("except:")
    lines.append(f"    source_catalog = {config.SOURCE_CATALOG!r}")
    lines.append("")
    lines.append("try:")
    lines.append("    source_schema = dbutils.widgets.get(\"source_schema\")")
    lines.append("except:")
    lines.append(f"    source_schema = {config.SOURCE_SCHEMA!r}")
    lines.append("")
    lines.append("try:")
    lines.append("    target_table = dbutils.widgets.get(\"target_table\")")
    lines.append("except:")
    lines.append(f"    target_table = {config.ENTITY!r}")
    lines.append("")
    lines.append("print(f\"Setup Parameters:\")")
    lines.append("print(f\"  DQ Catalog:     {catalog}\")")
    lines.append("print(f\"  DQ Schema:      {dq_schema}\")")
    lines.append("print(f\"  Source Catalog: {source_catalog}\")")
    lines.append("print(f\"  Source Schema:  {source_schema}\")")
    lines.append("print(f\"  Target Table:   {target_table}\")")
    lines.append("")
    return "\n".join(lines)


def _new_generic_rules_block(config):
    lines = []
    lines.append("new_generic_rules = [")
    for r in config.NEW_GENERIC_RULES:
        lines.append("    Row(")
        lines.append(f"        generic_rule_desc_short={r['generic_rule_desc_short']!r},")
        lines.append(f"        rule_description={r['rule_description']!r},")
        lines.append(f"        dq_category={r['dq_category']!r},")
        lines.append(f"        rule_detail={r['rule_detail']!r},")
        lines.append(f"        rule_logic_template={r['rule_logic_template']!r},")
        lines.append(f"        applicable_types={r['applicable_types']!r},")
        lines.append(f"        bcbs239_principle={r['bcbs239_principle']!r},")
        lines.append(f"        solvencyii_pillar={r['solvencyii_pillar']!r},")
        lines.append("        active=1, created_date=date.today(), created_by='dq-framework'")
        lines.append("    ),")
    lines.append("]")
    lines.append("")
    lines.append("spark.createDataFrame(new_generic_rules).createOrReplaceTempView(\"_new_rules_staging\")")
    lines.append("spark.sql(f\"\"\"")
    lines.append("    MERGE INTO {catalog}.{dq_schema}.dq_rules_generic AS target")
    lines.append("    USING _new_rules_staging AS source")
    lines.append("    ON target.generic_rule_desc_short = source.generic_rule_desc_short")
    lines.append("    WHEN NOT MATCHED THEN INSERT (")
    lines.append("        generic_rule_desc_short, rule_description, dq_category, rule_detail,")
    lines.append("        rule_logic_template, applicable_types, bcbs239_principle, solvencyii_pillar,")
    lines.append("        active, created_date, created_by")
    lines.append("    ) VALUES (")
    lines.append("        source.generic_rule_desc_short, source.rule_description, source.dq_category,")
    lines.append("        source.rule_detail, source.rule_logic_template, source.applicable_types,")
    lines.append("        source.bcbs239_principle, source.solvencyii_pillar,")
    lines.append("        source.active, source.created_date, source.created_by")
    lines.append("    )")
    lines.append("\"\"\")")
    lines.append(f"print(\"Merged {len(config.NEW_GENERIC_RULES)} new generic rule(s) into dq_rules_generic.\")")
    lines.append("spark.table(f\"{catalog}.{dq_schema}.dq_rules_generic\")")
    lines.append("    .select(\"generic_rule_id\", \"generic_rule_desc_short\", \"dq_category\")")
    lines.append("    .show(25, truncate=False)")
    lines.append("")
    return "\n".join(lines)


def _validation_request_block(config):
    lines = []
    lines.append(
        "spark.sql(f\"CREATE TABLE IF NOT EXISTS {catalog}.{dq_schema}.dq_validation_request "
        "(dq_val_request_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), "
        "dq_validation_request_short STRING NOT NULL, owner_dept STRING, owner_user STRING, "
        "active INTEGER, created_date DATE, created_by STRING) USING DELTA "
        "COMMENT 'DQ validation request registry.'\")"
    )
    lines.append("")
    lines.append("vr_rows = [Row(")
    lines.append(f"    dq_validation_request_short={config.DQ_VAL_REQUEST_SHORT!r},")
    lines.append(f"    owner_dept={config.OWNER_DEPT!r}, owner_user={config.OWNER_USER!r},")
    lines.append("    active=1, created_date=date.today(), created_by='dq-framework'")
    lines.append(")]")
    lines.append("spark.createDataFrame(vr_rows).createOrReplaceTempView(\"_dq_vr_staging\")")
    lines.append("spark.sql(f\"\"\"")
    lines.append("    MERGE INTO {catalog}.{dq_schema}.dq_validation_request AS target")
    lines.append("    USING _dq_vr_staging AS source")
    lines.append("    ON target.dq_validation_request_short = source.dq_validation_request_short")
    lines.append("    WHEN NOT MATCHED THEN INSERT (")
    lines.append("        dq_validation_request_short, owner_dept, owner_user, active, created_date, created_by")
    lines.append("    ) VALUES (")
    lines.append("        source.dq_validation_request_short, source.owner_dept, source.owner_user,")
    lines.append("        source.active, source.created_date, source.created_by")
    lines.append("    )")
    lines.append("\"\"\")")
    lines.append("spark.table(f\"{catalog}.{dq_schema}.dq_validation_request\").show(truncate=False)")
    lines.append("")
    lines.append("# Look up actual auto-assigned dq_val_request_id")
    lines.append("vr_id_row = (")
    lines.append("    spark.table(f\"{catalog}.{dq_schema}.dq_validation_request\")")
    lines.append(f"    .filter(F.col(\"dq_validation_request_short\") == {config.DQ_VAL_REQUEST_SHORT!r})")
    lines.append("    .select(\"dq_val_request_id\").collect()")
    lines.append(")")
    lines.append("dq_vr_id = int(vr_id_row[0][\"dq_val_request_id\"]) if vr_id_row else 1")
    lines.append("print(f\"dq_val_request_id for this entity = {dq_vr_id}\")")
    lines.append("")
    return "\n".join(lines)


def _copy_table_block(config):
    lines = []
    lines.append("source_full = f\"{source_catalog}.{source_schema}.{target_table}\"")
    lines.append("target_full = f\"{catalog}.{dq_schema}.{target_table}\"")
    lines.append("")
    lines.append("if spark.catalog.tableExists(target_full):")
    lines.append("    count = spark.table(target_full).count()")
    lines.append("    print(f\"Table {target_full} already exists with {count} rows - skipping copy.\")")
    lines.append("else:")
    lines.append("    df = spark.table(source_full)")
    lines.append("    df.write.format(\"delta\").saveAsTable(target_full)")
    lines.append("    count = spark.table(target_full).count()")
    lines.append("    print(f\"Copied {count} rows from {source_full} to {target_full}\")")
    lines.append("    print(f\"Columns ({len(df.columns)}): {df.columns}\")")
    lines.append("")
    return "\n".join(lines)


def _rule_mappings_block(config):
    lines = []

    # CREATE TABLE IF NOT EXISTS
    lines.append(
        "spark.sql(f\"CREATE TABLE IF NOT EXISTS {catalog}.{dq_schema}.dq_rule_mappings "
        "(rule_mapping_id BIGINT, dq_rule_no STRING NOT NULL, dq_val_request_id BIGINT, "
        "generic_rule_desc_short STRING NOT NULL, source_catalog STRING, source_schema STRING, "
        "source_table STRING, source_field STRING, rule_description STRING, threshold_pct DOUBLE, "
        "dq_category STRING, owner_dept STRING, owner_user STRING, active INTEGER, "
        "created_date DATE, created_by STRING) USING DELTA "
        "COMMENT 'DQ rule-to-field mappings.'\")"
    )
    lines.append("")

    # emit raw_mappings list
    lines.append("# (mapping_id, generic_rule_desc_short, field, description, threshold_pct, dq_category)")
    lines.append("raw_mappings = [")
    for m in config.MAPPINGS:
        mid, rule, field, desc, thr, cat = m
        lines.append(f"    ({mid}, {rule!r}, {field!r},")
        lines.append(f"     {desc!r},")
        lines.append(f"     {thr}, {cat!r}),")
    lines.append("]")
    lines.append("")

    # runtime Row construction
    lines.append("mapping_rows = []")
    lines.append("for m in raw_mappings:")
    lines.append("    safe_field = m[2].replace('|', '_vs_')")
    lines.append("    rule_short = '_'.join(m[1].split('_')[2:])")
    lines.append("    dq_rule_no = f\"DQ_{m[0]}_{rule_short}_{safe_field}\"")
    lines.append("    mapping_rows.append(Row(")
    lines.append("        rule_mapping_id=m[0], dq_rule_no=dq_rule_no, dq_val_request_id=dq_vr_id,")
    lines.append("        generic_rule_desc_short=m[1],")
    lines.append("        source_catalog=catalog, source_schema=dq_schema,")
    lines.append("        source_table=target_table, source_field=m[2],")
    lines.append("        rule_description=m[3], threshold_pct=m[4], dq_category=m[5],")
    lines.append(f"        owner_dept={config.OWNER_DEPT!r}, owner_user={config.OWNER_USER!r},")
    lines.append("        active=1, created_date=date.today(), created_by='dq-framework'")
    lines.append("    ))")
    lines.append("")
    lines.append("spark.createDataFrame(mapping_rows).createOrReplaceTempView(\"_dq_mappings_staging\")")
    lines.append("spark.sql(f\"\"\"")
    lines.append("    MERGE INTO {catalog}.{dq_schema}.dq_rule_mappings AS target")
    lines.append("    USING _dq_mappings_staging AS source")
    lines.append("    ON target.rule_mapping_id = source.rule_mapping_id")
    lines.append("    WHEN NOT MATCHED THEN INSERT (")
    lines.append("        rule_mapping_id, dq_rule_no, dq_val_request_id, generic_rule_desc_short,")
    lines.append("        source_catalog, source_schema, source_table, source_field,")
    lines.append("        rule_description, threshold_pct, dq_category, owner_dept, owner_user,")
    lines.append("        active, created_date, created_by")
    lines.append("    ) VALUES (")
    lines.append("        source.rule_mapping_id, source.dq_rule_no, source.dq_val_request_id,")
    lines.append("        source.generic_rule_desc_short, source.source_catalog, source.source_schema,")
    lines.append("        source.source_table, source.source_field, source.rule_description,")
    lines.append("        source.threshold_pct, source.dq_category, source.owner_dept, source.owner_user,")
    lines.append("        source.active, source.created_date, source.created_by")
    lines.append("    )")
    lines.append("\"\"\")")
    lines.append(f"print(f\"Merged {len(config.MAPPINGS)} rule mappings for {{target_table}}.\")")
    lines.append("")
    lines.append("spark.table(f\"{catalog}.{dq_schema}.dq_rule_mappings\")")
    lines.append("    .filter(F.col(\"source_table\") == target_table)")
    lines.append("    .select(\"rule_mapping_id\", \"dq_rule_no\", \"generic_rule_desc_short\",")
    lines.append("            \"source_field\", \"dq_category\")")
    lines.append("    .orderBy(\"rule_mapping_id\")")
    lines.append(f"    .show({len(config.MAPPINGS) + 2}, truncate=False)")
    lines.append("")
    return "\n".join(lines)
